# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e869c150bf869b471971fd6d9442589a75a08a7b12f3869bf3cac773532fbb414662870436be81757634e1625149d8feed82d2c262e20b31d9cfcfc841dd298

test:
  secret_key_base: 6566d491b1bd92e32ffa33b755472dabb19f45f35282bfb590ae0483ffe00f5e625b9f2048b5e51188f7a8b69f385861e4d12f2f3111167e4126fbf9216c40bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
